# Generated by Django 3.2 on 2021-05-21 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('hp', models.IntegerField()),
                ('cc', models.IntegerField()),
                ('type', models.CharField(max_length=20)),
                ('year_made', models.DateField()),
            ],
        ),
    ]
